# https://github.com/standard/eslint-config-standard-with-typescript
# https://github.com/standard/eslint-config-standard-react
# parser: babel-eslint
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: false
extends:
  - standard
  # - standard-jsx
  - standard-react
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
rules:
  comma-dangle:
    - error
    - always-multiline
  "@typescript-eslint/no-base-to-string":
    - error
    - ignoredTypeNames:
      - RegExp
      - Data
